markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Juan P. Schwindt
production_url : http://www.schwindt.org
description: "Hackeando Ruby desde Buenos Aires, Argentina"
disqus_shortname: jschwindtblog
analytics: UA-4532575-1
author :
  name : Juan Schwindt
  github : jschwindt
  twitter : jschwindt
  email: juan@schwindt.org
